/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ActionDialog.java
 *
 * Created on 18-ago-2009, 22:05:56
 */

package es.bitsonfire.perfectday.gui;

import es.bitsonfire.perfectday.model.ActionHelpInformation;
import es.bitsonfire.perfectday.model.Context;
import java.util.Iterator;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListDataListener;

/**
 *
 * @author Miguel Angel Lopez Montellano (alakat@gmail.com)
 */
public class ActionDialog extends javax.swing.JDialog {

    class ActionsComboBoxModel implements ComboBoxModel{

        ActionHelpInformation selected;
        @Override
        public void setSelectedItem(Object anItem) {
            selected = (ActionHelpInformation) anItem;
        }

        @Override
        public Object getSelectedItem() {
            return selected;
        }

        @Override
        public int getSize() {
            return manager.getSelectedContext().getActions().size();
        }

        @Override
        public Object getElementAt(int index) {
            Iterator<ActionHelpInformation> i = manager.getSelectedContext().getActions().iterator();
            for(int j=0;j<index;j++){
                i.next();
            }
            return i.next();
        }

        @Override
        public void addListDataListener(ListDataListener l) {
        }

        @Override
        public void removeListDataListener(ListDataListener l) {
        }

    }


    private ComboBoxModel previewAction = new ActionsComboBoxModel();
    private ComboBoxModel nextAction = new ActionsComboBoxModel();
    private ComboBoxModel intAction1 = new ActionsComboBoxModel();
    private ComboBoxModel intAction2 = new ActionsComboBoxModel();
    private ComboBoxModel intAction3 = new ActionsComboBoxModel();
    private HelperManager manager;
    private ActionHelpInformation action;
    /** Creates new form ActionDialog */
    public ActionDialog(java.awt.Frame parent, boolean modal,HelperManager manager) {
        super(parent, modal);
        this.manager = manager;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tTitulo = new javax.swing.JTextField();
        asadf = new javax.swing.JScrollPane();
        aresumen = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        acompleto = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        cbPrview = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cbNext = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cbInteres1 = new javax.swing.JComboBox();
        cbInterest2 = new javax.swing.JComboBox();
        cbInterest3 = new javax.swing.JComboBox();
        guardar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva Información de acción");
        setModal(true);

        jLabel1.setText("Título");

        tTitulo.setToolTipText("Máximo 50 carácteres");

        asadf.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumen"));
        asadf.setToolTipText("Máximo 255 caractéres");
        asadf.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        aresumen.setColumns(20);
        aresumen.setRows(5);
        asadf.setViewportView(aresumen);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Texto completo de ayuda"));
        jScrollPane1.setToolTipText("No hay máximo pero se recomienda textos cortos");

        acompleto.setColumns(20);
        acompleto.setRows(5);
        jScrollPane1.setViewportView(acompleto);

        jLabel2.setText("Anterior");

        cbPrview.setModel(previewAction);
        cbPrview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPrviewActionPerformed(evt);
            }
        });

        jLabel3.setText("Siguiente");

        cbNext.setModel(nextAction);

        jLabel4.setText("Relacionados");

        cbInteres1.setModel(intAction1);

        cbInterest2.setModel(intAction2);

        cbInterest3.setModel(intAction3);

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                    .addComponent(asadf, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPrview, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbNext, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbInteres1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(guardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbInterest2, javax.swing.GroupLayout.Alignment.TRAILING, 0, 105, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbInterest3, 0, 102, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asadf, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbPrview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbInteres1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbInterest2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbInterest3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar)
                    .addComponent(cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        //TODO readaptar
        if(this.tTitulo.getText().length()>50)
            this.tTitulo.setText(this.tTitulo.getText().substring(0,47)+"...");

        if(this.aresumen.getText().length()>255)
            this.aresumen.setText(this.aresumen.getText().substring(0,252)+"...");
        //TODO validar
        this.action= new ActionHelpInformation(0, this.tTitulo.getText(), this.aresumen.getText(), this.acompleto.getText()    );
        this.action.setNext((ActionHelpInformation) nextAction.getSelectedItem());
        this.action.setPreview((ActionHelpInformation) previewAction.getSelectedItem());
        if(cbInteres1.getSelectedItem()!=null)
            this.action.getInteresting().add((ActionHelpInformation)cbInteres1.getSelectedItem());
        if(cbInterest2.getSelectedItem()!=null)
            this.action.getInteresting().add((ActionHelpInformation)cbInterest2.getSelectedItem());
        if(cbInterest3.getSelectedItem()!=null)
            this.action.getInteresting().add((ActionHelpInformation)cbInterest3.getSelectedItem());
        this.manager.addActionHelpInformation(action);

        this.dispose();
        JOptionPane.showMessageDialog(this, "La información se ha guardado correctamente");
    }//GEN-LAST:event_guardarActionPerformed

    private void cbPrviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPrviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPrviewActionPerformed

    /**
     *
     * @return
     */
    public ActionHelpInformation getAction() {
        return action;
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea acompleto;
    private javax.swing.JTextArea aresumen;
    private javax.swing.JScrollPane asadf;
    private javax.swing.JButton cancelar;
    private javax.swing.JComboBox cbInteres1;
    private javax.swing.JComboBox cbInterest2;
    private javax.swing.JComboBox cbInterest3;
    private javax.swing.JComboBox cbNext;
    private javax.swing.JComboBox cbPrview;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tTitulo;
    // End of variables declaration//GEN-END:variables

}
