/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InitialSplashPage.java
 *
 * Created on 20-ago-2009, 18:30:07
 */

package org.perfectday.dashboard.gui.dialog;

/**
 *
 * @author Miguel Angel Lopez Montellano (alakat@gmail.com)
 */
public class InitialSplashPage extends javax.swing.JDialog {


    /** Creates new form InitialSplashPage */
    public InitialSplashPage(java.awt.Frame parent, boolean modal,String up, String dw) throws InterruptedException {
        super(parent, modal);
        initComponents();
        this.taDw.setBackground(this.getBackground());
        this.taUp.setBackground(this.getBackground());
        this.taDw.setText(dw);
        this.taUp.setText(up);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taUp = new javax.swing.JTextArea();
        taDw = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        taUp.setColumns(20);
        taUp.setEditable(false);
        taUp.setFont(new java.awt.Font("Freestyle Script", 0, 14)); // NOI18N
        taUp.setLineWrap(true);
        taUp.setRows(5);
        taUp.setWrapStyleWord(true);

        taDw.setColumns(20);
        taDw.setEditable(false);
        taDw.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        taDw.setLineWrap(true);
        taDw.setRows(5);
        taDw.setWrapStyleWord(true);
        taDw.setAutoscrolls(false);
        taDw.setEnabled(false);
        taDw.setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(taDw, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                    .addComponent(taUp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taUp, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taDw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea taDw;
    private javax.swing.JTextArea taUp;
    // End of variables declaration//GEN-END:variables

}
