/*
 * loadingDialog.java
 *
 * Created on 9 de septiembre de 2008, 19:29
 */

package org.perfectday.dashboard.gui;

import javax.swing.JTextArea;
import org.perfectday.core.asf.State;

/**
 *
 * @author  Lobo
 */
public class LoadingDialog extends java.awt.Dialog {

    /** Creates new form loadingDialog */
    public LoadingDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jProgressBar1.setIndeterminate(true);
        this.setTitle("Cargando partida....");
        jProgressBar1.setMaximum(7);
        jProgressBar1.setValue(0);
        jProgressBar1.setIndeterminate(false);
    }

    public void addState(State actual) {
        this.areaDialogoCarga.append("\nEstado actual: "+actual.getMovements().get(0).getName());
        this.jProgressBar1.setValue(this.jProgressBar1.getValue()+1);
    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaDialogoCarga = new javax.swing.JTextArea();
        jProgressBar1 = new javax.swing.JProgressBar();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        areaDialogoCarga.setColumns(20);
        areaDialogoCarga.setEditable(false);
        areaDialogoCarga.setRows(5);
        areaDialogoCarga.setText("Estableciendo Conexion");
        jScrollPane1.setViewportView(areaDialogoCarga);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jProgressBar1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargando."));
        jPanel1.add(jProgressBar1, java.awt.BorderLayout.PAGE_END);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

   public JTextArea getAreaDialogCarga(){
     return this.areaDialogoCarga;
   }
   
   public void closeWindows(){
       this.setVisible(false);
       this.dispose();
       
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDialogoCarga;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
