/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.perfectday.dashboard.gui;

import java.lang.reflect.InvocationTargetException;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;
import org.perfectday.dashboard.Main;
import org.perfectday.dashboard.exception.GameBuilderException;
import org.perfectday.dashboard.threads.DashBoardThreadGroup;
import org.perfectday.gamebuilder.GameBuilder;
import org.perfectday.gamebuilder.GameBuilderFactory;
import org.perfectday.gamebuilder.model.BattleDescription;

/**
 *
 * @author Miguel (alakat@gmail.com)
 */
public class MainMenu extends javax.swing.JFrame {

    
    private static final Logger logger =
            Logger.getLogger(MainMenu.class);
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        multijugador = new javax.swing.JButton();
        unjugador = new javax.swing.JButton();
        about = new javax.swing.JButton();
        preferencias = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        multijugador.setText("Multijugador");
        multijugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multijugadorActionPerformed(evt);
            }
        });

        unjugador.setText("Un Jugador");
        unjugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unjugadorActionPerformed(evt);
            }
        });

        about.setText("Conocenos");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });

        preferencias.setText("Preferencias");
        preferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferenciasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unjugador, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(about, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multijugador, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addComponent(preferencias)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(preferencias)
                .addGap(48, 48, 48)
                .addComponent(unjugador, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(multijugador, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(about, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void multijugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multijugadorActionPerformed
        // TODO add your handling code here:
        new DashBoard(Main.userInit,Main.passInit).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_multijugadorActionPerformed

    private void unjugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unjugadorActionPerformed
        if (Thread.currentThread().getThreadGroup() instanceof DashBoardThreadGroup) {
            DashBoardThreadGroup dashBoardThreadGroup = 
                    (DashBoardThreadGroup) Thread.currentThread().getThreadGroup();
            if(dashBoardThreadGroup.inGame()){
                JOptionPane.showMessageDialog(this,
                        "Ya existe una partida en ejecución",
                        "PerfectDay. Información",
                        JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }

        DescriptionBattleDialog dbd = new DescriptionBattleDialog(null, true);
        dbd.setVisible(true);
        BattleDescription bd = null;
        if(dbd.isAcepted()){        
                try {
                    bd = dbd.getBattleDescription();
                    Logger.getLogger(ChatPanel.class).info("Mission:" + bd.getMission());
                    Logger.getLogger(ChatPanel.class).info("Public:" + bd.isBattlePublic());
                    Logger.getLogger(ChatPanel.class).info("Point:" + bd.getPoint());
                    GameBuilder bg = GameBuilderFactory.getInstance().createGameBuilderOnePlayer();
                    bg.setBattleDescription(bd);
                    try {   
                        bg.move();
                    } catch (IllegalAccessException ex) {
                        logger.error("Error de acceso ilegal",ex);

                        JOptionPane.showMessageDialog(this, "Error en las comunicaciones","Ha sido imposible iniciar el juego",JOptionPane.ERROR_MESSAGE);
                    } catch (InvocationTargetException ex) {
                        logger.error("invocacion ilegal",ex);

                        JOptionPane.showMessageDialog(this, "Error en las comunicaciones","Ha sido imposible iniciar el juego",JOptionPane.ERROR_MESSAGE);
                    }
                } catch (GameBuilderException ex) {
                    JOptionPane.showMessageDialog(this,ex.getMessage(), "PerfectDay. Información",JOptionPane.INFORMATION_MESSAGE);
                } catch (NoSuchMethodException ex) {
                    logger.error("Error al crear el constructor de partidas",ex);
                    JOptionPane.showMessageDialog(this, "Error en las comunicaciones","Ha sido imposible iniciar el juego",JOptionPane.ERROR_MESSAGE);
                }
        }else{
            Logger.getLogger(ChatPanel.class).info("Batalla cancelada");
        }
    }//GEN-LAST:event_unjugadorActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutActionPerformed

    private void preferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preferenciasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton about;
    private javax.swing.JButton multijugador;
    private javax.swing.JButton preferencias;
    private javax.swing.JButton unjugador;
    // End of variables declaration//GEN-END:variables
}
