/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.perfectday.main.dummyengine.dialog;

/**
 *
 * @author Miguel (alakat@gmail.com)
 */
public class DummyCombatDialog extends javax.swing.JDialog {

    /**
     * Creates new form DummyCombatDialog
     */
    public DummyCombatDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        backgroundLabel = new javax.swing.JLabel();
        miniInfoAtac = new org.perfectday.main.dummyengine.model.JMiniInfo();
        miniInfoDef = new org.perfectday.main.dummyengine.model.JMiniInfo();
        dummyCombatTextArea2 = new org.perfectday.main.dummyengine.component.DummyCombatTextArea();
        butonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dummy_assets/grass.png"))); // NOI18N
        jLayeredPane1.add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 744, 393);
        jLayeredPane1.add(miniInfoAtac);
        miniInfoAtac.setBounds(560, 10, 176, 134);
        jLayeredPane1.setLayer(miniInfoAtac, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane1.add(miniInfoDef);
        miniInfoDef.setBounds(10, 250, 176, 134);
        jLayeredPane1.setLayer(miniInfoDef, 2);
        jLayeredPane1.add(dummyCombatTextArea2);
        dummyCombatTextArea2.setBounds(40, 400, 650, 200);
        jLayeredPane1.setLayer(dummyCombatTextArea2, 3);

        butonClose.setText("OK");
        jLayeredPane1.add(butonClose);
        butonClose.setBounds(640, 550, 75, 29);
        jLayeredPane1.setLayer(butonClose, 4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton butonClose;
    private org.perfectday.main.dummyengine.component.DummyCombatTextArea dummyCombatTextArea2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private org.perfectday.main.dummyengine.model.JMiniInfo miniInfoAtac;
    private org.perfectday.main.dummyengine.model.JMiniInfo miniInfoDef;
    // End of variables declaration//GEN-END:variables
}
